# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConvectorCurrency.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 755)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("img/exchange.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("background-color: rgb(111, 111, 111);")
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 501, 221))
        self.frame.setStyleSheet("background-color: rgb(191, 0, 95);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.labelTitle = QtWidgets.QLabel(self.frame)
        self.labelTitle.setGeometry(QtCore.QRect(129, 0, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.labelTitle.setFont(font)
        self.labelTitle.setStyleSheet("color: rgb(255, 255, 255);")
        self.labelTitle.setObjectName("labelTitle")
        self.labelExchange_img = QtWidgets.QLabel(self.frame)
        self.labelExchange_img.setGeometry(QtCore.QRect(120, 50, 261, 161))
        self.labelExchange_img.setText("")
        self.labelExchange_img.setPixmap(QtGui.QPixmap("img/exchange.ico"))
        self.labelExchange_img.setObjectName("labelExchange_img")
        self.inputCurrency = QtWidgets.QLineEdit(self.centralwidget)
        self.inputCurrency.setGeometry(QtCore.QRect(60, 270, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inputCurrency.setFont(font)
        self.inputCurrency.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.inputCurrency.setStyleSheet("background-color: rgb(255, 10, 128);\n"
"border-color: rgb(170, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 30;")
        self.inputCurrency.setAlignment(QtCore.Qt.AlignCenter)
        self.inputCurrency.setObjectName("inputCurrency")
        self.inputAmount = QtWidgets.QLineEdit(self.centralwidget)
        self.inputAmount.setGeometry(QtCore.QRect(60, 380, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.inputAmount.setFont(font)
        self.inputAmount.setStyleSheet("background-color: rgb(255, 10, 128);\n"
"border-color: rgb(170, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 30;")
        self.inputAmount.setAlignment(QtCore.Qt.AlignCenter)
        self.inputAmount.setObjectName("inputAmount")
        self.exchangeBtn = QtWidgets.QPushButton(self.centralwidget)
        self.exchangeBtn.setGeometry(QtCore.QRect(60, 680, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.exchangeBtn.setFont(font)
        self.exchangeBtn.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 85, 255);\n"
"    border: 3 solid rgb(32, 44, 66);\n"
"    color: rgb(255, 255, 255);\n"
"    border-radius:30;\n"
"}\n"
"QPushButton:pressed{\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(255, 85, 255);\n"
"}\n"
"\n"
"")
        self.exchangeBtn.setObjectName("exchangeBtn")
        self.labelCurrencyInput = QtWidgets.QLabel(self.centralwidget)
        self.labelCurrencyInput.setGeometry(QtCore.QRect(0, 230, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.labelCurrencyInput.setFont(font)
        self.labelCurrencyInput.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.labelCurrencyInput.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurrencyInput.setObjectName("labelCurrencyInput")
        self.labelAmountInput = QtWidgets.QLabel(self.centralwidget)
        self.labelAmountInput.setGeometry(QtCore.QRect(0, 330, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.labelAmountInput.setFont(font)
        self.labelAmountInput.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.labelAmountInput.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAmountInput.setObjectName("labelAmountInput")
        self.outputAmount = QtWidgets.QLineEdit(self.centralwidget)
        self.outputAmount.setGeometry(QtCore.QRect(60, 490, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.outputAmount.setFont(font)
        self.outputAmount.setStyleSheet("background-color: rgb(255, 10, 128);\n"
"border-color: rgb(170, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 30;")
        self.outputAmount.setAlignment(QtCore.Qt.AlignCenter)
        self.outputAmount.setObjectName("outputAmount")
        self.labelCurrencyOutput = QtWidgets.QLabel(self.centralwidget)
        self.labelCurrencyOutput.setGeometry(QtCore.QRect(10, 440, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.labelCurrencyOutput.setFont(font)
        self.labelCurrencyOutput.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.labelCurrencyOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.labelCurrencyOutput.setObjectName("labelCurrencyOutput")
        self.outputCurrency = QtWidgets.QLineEdit(self.centralwidget)
        self.outputCurrency.setGeometry(QtCore.QRect(60, 600, 380, 60))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.outputCurrency.setFont(font)
        self.outputCurrency.setStyleSheet("background-color: rgb(255, 10, 128);\n"
"border-color: rgb(170, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius: 30;")
        self.outputCurrency.setAlignment(QtCore.Qt.AlignCenter)
        self.outputCurrency.setReadOnly(True)
        self.outputCurrency.setObjectName("outputCurrency")
        self.labelAmountOutput = QtWidgets.QLabel(self.centralwidget)
        self.labelAmountOutput.setGeometry(QtCore.QRect(0, 550, 501, 41))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.labelAmountOutput.setFont(font)
        self.labelAmountOutput.setStyleSheet("color: rgb(255, 255, 255);\n"
"")
        self.labelAmountOutput.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAmountOutput.setObjectName("labelAmountOutput")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ConvectorCurrency"))
        self.labelTitle.setText(_translate("MainWindow", "Currency Convector"))
        self.inputCurrency.setText(_translate("MainWindow", "USD"))
        self.inputAmount.setText(_translate("MainWindow", "100"))
        self.exchangeBtn.setText(_translate("MainWindow", "Exchange"))
        self.labelCurrencyInput.setText(_translate("MainWindow", "Enter your currency:"))
        self.labelAmountInput.setText(_translate("MainWindow", "Enter the amount of currency you want to exchange:"))
        self.outputAmount.setText(_translate("MainWindow", "UAH"))
        self.labelCurrencyOutput.setText(_translate("MainWindow", "Enter the currency you want to exchange:"))
        self.labelAmountOutput.setText(_translate("MainWindow", "The amount of currency you have exchanged:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
